CREATE TABLE IF NOT EXISTS Rules (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Regex TEXT NOT NULL CHECK (LENGTH(Regex) <= 50),
    Description TEXT NOT NULL CHECK (LENGTH(Description) <= 100),
    Active INTEGER NOT NULL CHECK (Active IN (0, 1))
);
